"""
Quality control for agent traces.
"""

import difflib
import json
import logging
from pathlib import Path
from typing import Tuple

logger = logging.getLogger(__name__)


class ValidationReason:
    VALID = "valid"
    FILE_CORRUPT = "file_corrupt"
    MISSING_RESULT = "result_file_missing"
    SUBOPTIMAL = "score_too_low"
    NO_FINISH = "no_finish_tool"
    ZOMBIE_LOOP = "zombie_loop"
    FORMAT_DEGRADATION = "format_degradation"
    ERROR_DENSITY = "high_error_density"


class TraceValidator:
    def __init__(
        self,
        min_score: float = 0.9,
        require_finish: bool = True,
        max_loop_similarity: float = 0.9,
        loop_window: int = 4,
        max_error_ratio: float = 0.1,
    ):
        """
        Args:
            min_score: Minimum normalized score (0.0-1.0) to accept.
                       Use 1.0 for perfect solutions, 0.0 to disable.
        """
        self.min_score = min_score
        self.require_finish = require_finish
        self.max_loop_similarity = max_loop_similarity
        self.loop_window = loop_window
        self.max_error_ratio = max_error_ratio

    def _calculate_similarity(self, text1: str, text2: str) -> float:
        if not text1 or not text2:
            return 0.0
        return difflib.SequenceMatcher(None, text1, text2).ratio()

    def validate(self, trace_path: Path) -> Tuple[bool, str]:
        # 1. Load Trace
        try:
            data = json.loads(trace_path.read_text())
        except Exception:
            return False, ValidationReason.FILE_CORRUPT

        # 2. Check Outcome (Optimality Gap)
        # We assume the companion result file exists (generated by the env).
        # It contains the ground truth score calculated by the oracle.
        result_path = trace_path.parent / trace_path.name.replace(
            ".trace.json", ".json"
        )

        if not result_path.exists():
            # If we enforce a score, we must have the result file.
            if self.min_score > 0.0:
                return False, ValidationReason.MISSING_RESULT
        else:
            try:
                res_data = json.loads(result_path.read_text())
                # Extract score. Usually nested in 'result' -> 'score'.
                # Default to 0.0 if missing.
                score = res_data.get("result", {}).get("score", 0.0)

                if score < self.min_score:
                    return False, ValidationReason.SUBOPTIMAL
            except Exception:
                # Malformed result file
                return False, ValidationReason.MISSING_RESULT

        # 3. Check Structure (Events)
        events = data.get("events", [])
        step_events = [e for e in events if e.get("type") == "StepEvent"]
        if not step_events:
            return False, ValidationReason.FILE_CORRUPT

        # 4. Check for Finish Call
        if self.require_finish:
            has_finish = False
            # Look in the code of the last few steps
            for step in reversed(step_events[-3:]):
                code = step.get("data", {}).get("code", "")
                if code and "finish" in code:
                    has_finish = True
                    break
            if not has_finish:
                return False, ValidationReason.NO_FINISH

        # 5. Check for Zombie Loops
        assistant_texts = [
            s.get("data", {}).get("assistant_text", "") for s in step_events
        ]
        if len(assistant_texts) >= self.loop_window:
            recent = assistant_texts[-self.loop_window :]
            last_msg = recent[-1]

            # Count similarity in the window
            high_sim_count = sum(
                1
                for prev in recent[:-1]
                if self._calculate_similarity(last_msg, prev) > self.max_loop_similarity
            )

            if high_sim_count >= (self.loop_window - 1):
                return False, ValidationReason.ZOMBIE_LOOP

        # 6. Check for Error Density
        error_count = 0

        # ERRORS TO IGNORE (Valuable Training Signals):
        # 1. ToolRuntimeException: The agent learning hidden constraints (e.g., "Item class 'J' not allowed")
        # 2. Tool call limit: The agent hitting the "per-step tool limit" designed to force iterative behavior
        allowed_error_substrings = [
            "codeact_runtime.codeact.tool.ToolRuntimeException",
            "Tool call limit exceeded",
        ]

        for step in step_events:
            # We look at the result of the code execution
            res = step.get("data", {}).get("interpreter_result") or {}
            error_msg = res.get("error", "")

            if error_msg:
                # If the error is one of our "good" errors, we skip counting it.
                # These are observations the model must learn to recover from.
                if any(allowed in error_msg for allowed in allowed_error_substrings):
                    continue

                # Any other error (e.g., SyntaxError, NameError) is a sign of competency failure.
                # We log these to help you debug if needed.
                # logger.warning(f"Rejecting trace {trace_path.name} due to error: {error_msg}")
                error_count += 1

        # Calculate density based only on "bad" errors
        if (
            len(step_events) > 0
            and (error_count / len(step_events)) > self.max_error_ratio
        ):
            return False, ValidationReason.ERROR_DENSITY

        return True, ValidationReason.VALID
